sudo: required
services:
    - docker

before_install:
    - docker build -t alanhood77/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true alanhood77/react-test npm test

after_success:
    - docker build -t alanhood77/multi-client ./client
    - docker build -t alanhood77/multi-nginx ./nginx
    - docker build -t alanhood77/multi-server ./server
    - docker build -t alanhood77/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take these images and push to Docker hub
    - docker push alanhood77/multi-client
    - docker push alanhood77/multi-nginx
    - docker push alanhood77/multi-server
    - docker push alanhood77/multi-worker